spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:tc:postgresql:15:///postgres
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: create
jwt:
  secret: 413F4428472B4B6250655368566D5970337336763979244226452948404D6351
---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
jwt:
  secret: 413F4428472B4B6250655368566D5970337336763979244226452948404D6351
---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:postgresql://postgres_bill_splitter:5432/postgres
    username: ${POSTGRES_PROD_USER:postgres}
    password: ${POSTGRES_PROD_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: update
jwt:
  secret: 413F4428472B4B6250655368566D5970337336763979244226452948404D6351

springdoc:
  api-docs:
    enabled: false